---
build_from:
  amd64: ghcr.io/home-assistant/amd64-base:latest
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
args:
  OPENGYM_REF: main
labels:
  org.opencontainers.image.title: openGym
  org.opencontainers.image.description: Self-hosted gym & body-weight tracker
  org.opencontainers.image.source: https://gitlab.com/DuarteSantos8/opengym
  org.opencontainers.image.licenses: AGPL-3.0-or-later
